name: mirror
description: "Basit bir sosyal medya uygulamasi."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  async: ^2.12.0
  http: ^1.2.2
  image_picker: ^1.1.2
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3

flutter:
  uses-material-design: false
  assets:
    - assets/login_logo.png
    - assets/default.jpg